--                  Project: Querying a Large Relational Database

-- 3. Perform the following with help of the above database:

/* a. Get all the details from the person table including email ID, phone
number and phone number type */

SELECT P.BUSINESSENTITYID, P.FIRSTNAME, P.LASTNAME, P.EMAILPROMOTION, E.EMAILADDRESS, PH.PHONENUMBER,
PT.NAME AS PHONENUMBERTYPE FROM PERSON.PERSON P
LEFT JOIN
       PERSON.EMAILADDRESS E ON P.BUSINESSENTITYID = E.BUSINESSENTITYID
LEFT JOIN
       PERSON.PERSONPHONE PH ON P.BUSINESSENTITYID = PH.BUSINESSENTITYID
LEFT JOIN
       PERSON.PHONENUMBERTYPE PT ON PH.PHONENUMBERTYPEID = PT.PHONENUMBERTYPEID   

   
-- b. Get the details of the sales header order made in May 2011

SELECT SALESORDERID, ORDERDATE, TOTALDUE FROM SALES.SALESORDERHEADER WHERE
YEAR(ORDERDATE) = 2011 AND MONTH(ORDERDATE) = 5


-- c. Get the details of the sales details order made in the month of May 2011

SELECT SOD.SALESORDERID, P.NAME AS PRODUCTNAME, SOD.ORDERQTY, SOD.UNITPRICE, SOD.LINETOTAL 
FROM SALES.SALESORDERDETAIL SOD
JOIN
     PRODUCTION.PRODUCT P ON SOD.PRODUCTID = P.PRODUCTID
JOIN
     SALES.SALESORDERHEADER SOH ON SOD.SALESORDERID = SOH.SALESORDERID
WHERE
     YEAR(SOH.ORDERDATE) = 2011 AND MONTH(SOH.ORDERDATE) = 5
	   	 

-- d. Get the total sales made in May 2011

SELECT SUM(TOTALDUE) AS TOTALSALES FROM SALES.SALESORDERHEADER WHERE YEAR(ORDERDATE) = 2011 AND
MONTH(ORDERDATE) = 5
 

-- e. Get the total sales made in the year 2011 by month order by increasing sales

SELECT MONTH(ORDERDATE) AS MONTH, SUM(TOTALDUE) AS TOTALSALES FROM SALES.SALESORDERHEADER WHERE
YEAR(ORDERDATE) = 2011 GROUP BY MONTH(ORDERDATE) ORDER BY MONTH

-- f. Get the total sales made to the customer with FirstName='Gustavo' and LastName = 'Achong'

SELECT C.FIRSTNAME, C.LASTNAME, SUM(SOH.TOTALDUE) AS TOTALSALES FROM PERSON.PERSON C
JOIN
    SALES.CUSTOMER CUST ON C.BUSINESSENTITYID = CUST.PERSONID
JOIN
    SALES.SALESORDERHEADER SOH ON CUST.CUSTOMERID = SOH.CUSTOMERID
WHERE C.FIRSTNAME = 'GUSTAVO' AND C.LASTNAME = 'ACHONG' GROUP BY C.FIRSTNAME, C.LASTNAME
   